import { useQuery } from "@tanstack/react-query";
import { Archive, Download, QrCode } from "lucide-react";
import { downloadLetter, fetchArchive } from "../api/letters";

export function LetterArchivePage() {
  const { data, isLoading } = useQuery({ queryKey: ["letters", "archive"], queryFn: fetchArchive });
  const download = async (id: string, name: string) => { const blob = await downloadLetter(id, "final"); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url); };
  return <div className="p-8"><div className="mb-6 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-100 text-brand-800"><Archive size={20}/></div><div><h1 className="text-xl font-semibold">Fayllar arxivi</h1><p className="text-sm text-slate-500">Rahbariyat tasdiqlagan xatlar va QR tasdiq nusxalari</p></div></div><div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Raqam</th><th className="px-4 py-3">Kimga</th><th className="px-4 py-3">Tasdiqlangan sana</th><th className="px-4 py-3">QR</th><th className="px-4 py-3">Fayl</th></tr></thead><tbody className="divide-y divide-slate-100">{isLoading ? <tr><td colSpan={5} className="px-4 py-8 text-center">Yuklanmoqda...</td></tr> : data?.map((x:any)=><tr key={x.id}><td className="px-4 py-4">№ {x.documentNumber}</td><td className="px-4 py-4 font-medium">{x.counterpartyName}</td><td className="px-4 py-4 text-slate-500">{x.approvedAt ? new Date(x.approvedAt).toLocaleString("uz-UZ") : "—"}</td><td className="px-4 py-4 text-emerald-700"><QrCode size={18}/></td><td className="px-4 py-4"><button onClick={()=>download(x.id, x.finalFileUrl?.split('/').pop() || `xat-${x.documentNumber}.docx`)} className="flex items-center gap-2 rounded-lg bg-brand-800 px-3 py-2 text-xs font-medium text-white"><Download size={14}/> Yuklab olish</button></td></tr>)}</tbody></table></div></div>;
}
